@startuml
scale 500*500

(*) --> "<b>Assiégement de la 1ère garde en demi-bocle</b>\n<img:images/msI.33/P01E1 - §005.jpg>" as assiegementdemibocle1ere
assiegementdemibocle1ere -->[contre] "<b>Coup bas</b>\n<i>Non illustré</i>" as coupbas
assiegementdemibocle1ere-->[suite]"<b>Coup de pointe</b>\n<i>Non illustré</i>" as couppointe
assiegementdemibocle1ere-right->[contre]"<b>Plongée sous la demi-bocle</b>\n<img:images/msI.33/P01E2 - §006.jpg>" as plongee

coupbas-->[contre]"<b>Coup à la tête</b>\n<i>Non illustré</i>" as couptete

plongee-right->[contre]"<b>Liage supérieur droit</b>\n<img:images/msI.33/P01E3 - §007.jpg>" as liagesupdroit
plongee-->[contre]"<b>Coup à la tête</b>\n<i>Non illustré</i>" as coupteteordinaire

liagesupdroit-right->[suite]"<b>Coup de bocle et coup à la tête</b>\n<img:images/msI.33/P01E4 - §008.jpg>" as coupboclecouptete

liagesupdroit-->[contre]"<b>Protection en crosse</b>\n<img:images/msI.33/P21E2 - §069.jpg>\n<i>P03E2;P13E2;P21E2;P39E3</i>" as protectioncrosse
liagesupdroit-->[suite]"<b>Encerclement des bras avec la main gauche</b>\nEn tournant le dos\n<i>Non illustré</i>" as encerclementgauchedos
protectioncrosse-->[suite]"<b>Encerclement des bras avec la main gauche</b>\nDe face\n<img:images/msI.33/P03E3 - §016.jpg>" as encerclementgaucheface
protectioncrosse-->[suite]"<b>Mutation</b>\n<img:images/msI.33/P02E4 - §012.jpg>" as mutation
protectioncrosse-->[suite]"<b>Passage</b>\n après un liage supérieur droit\n<img:images/msI.33/P39E4 - §120.jpg>" as passage
protectioncrosse-->[suite]"<b>Encerclement des bras avec la main droite</b>\nEn tournant le dos\n\n<img:images/msI.33/P21E4 - §071.jpg>" as encerclementdroit
protectioncrosse-->[contre]coupboclecouptete

mutation-->[suite]"<b>Nuckem</b>\nCoup séparant l'épée et la bocle\n<img:images/msI.33/P02E5 - §013.jpg>" as nuckem

encerclementgauchedos-->[contre] "<b>Lutte</b>\n<img:images/msI.33/P21E5 - §072.jpg>" as lutte
encerclementdroit-->[contre]lutte
lutte-->[contre] "<b>Volte</b>\n<img:images/msI.33/P21E5 - §073.jpg>" as volte

encerclementgaucheface-->(*)
encerclementgauchedos-->(*)
volte-->(*)
coupboclecouptete-->(*)
couptete-->(*)
couppointe-->(*)
coupteteordinaire-->(*)
passage-->(*)
nuckem-->(*)

'======
'Layout
'======
'First line
encerclementgauchedos-right[hidden]->encerclementgaucheface
'encerclementdroit-right[hidden]->encerclementgaucheface
encerclementdroit-right[hidden]->mutation
mutation-right[hidden]->passage
coupteteordinaire-right[hidden]->encerclementgaucheface
coupbas-right[hidden]->coupteteordinaire

'second line
lutte-right[hidden]->nuckem
'couptete-right[hidden]->lutte
couptete-up[hidden]->coupbas
coupbas-right[hidden]->couppointe
couppointe-right[hidden]->coupteteordinaire

@enduml